name: mkdocs
on:
  push:
    branches:
      - main
      - test_cov_upload
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ">= 3.8 < 3.12"
      - name: Install doc dependencies
        run: |
          pip install -r docs/requirements.txt
      - name: Install torchcvnn
        run: pip install .

      - name: Download code coverage report
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: pytest
          branch: test_cov_upload
          name: coverage_report
          path: htmlcov
      - name: Generate and deploy the documentation
        run: mkdocs gh-deploy --force --clean --verbose
